[package]
name = "arcade_jump"
description = "Arcade jump trajectory configurator"
authors.workspace = true
version.workspace = true
edition.workspace = true

[features]
default = ["std"]

# enable support for the standard library
std = ["num-traits/std", "thiserror/std"]

[dependencies]
num-traits = { version = "0.2", default-features = false }
thiserror = { version = "2.0", default-features = false }
lazy_static = { version = "1.5", features = ["spin_no_std"] }
arcade_jump_macros = { path = "../arcade_jump_macros" }
